version: '3'
services:
  composer:
    container_name: stwarog-uow
    image: composer:1.1 # for 7.1 php version
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    entrypoint: composer
